[package]
name = "memfd_play_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memfd = "0.6.4"
nix = { version = "0.27.1", features = ["fs", "process"] }
cstr = "0.2.11"
